project_name = "zari_test"
root = "templates"
out_root = "output"
profile_path = "profiles/go_datastar_profile"

[[templates]]

path = "app/cmd/web/handlers.mako.go"
copy_mode = "once"

[[templates]]

path = "app/internal/views/model_admin.mako.templ"
out_name = "${name}_admin.templ"
copy_mode = "per_model"

[[templates]]

path = "app/internal/views/model_display.mako.templ"
out_name = "${name}_display.templ"
copy_mode = "per_model"

[[templates]]

path = "app/internal/views/model_ui_builder.mako.go"
out_name = "${name}_ui_builder.go"
copy_mode = "per_model"

[[templates]]

path = "app/models/model.mako.go"
out_name = "${name}_model.go"
copy_mode = "per_model"